grantPermissions:
	chmod 766 ../bin/*

run:
	../bin/run.sh

runA:
	../bin/run.sh -a

runMany:
	python3 RLalgos.py --dqnAgent_epsDecay 0.999 --dqnAgent_lr 1e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.999 --dqnAgent_lr 2.782559402207126e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.999 --dqnAgent_lr 7.742636826811278e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.999 --dqnAgent_lr 0.00021544346900318823
	python3 RLalgos.py --dqnAgent_epsDecay 0.999 --dqnAgent_lr 0.0005994842503189409
	python3 RLalgos.py --dqnAgent_epsDecay 0.999 --dqnAgent_lr 0.0016681005372000592
	python3 RLalgos.py --dqnAgent_epsDecay 0.999 --dqnAgent_lr 0.004641588833612777
	python3 RLalgos.py --dqnAgent_epsDecay 0.999 --dqnAgent_lr 0.012915496650148827
	python3 RLalgos.py --dqnAgent_epsDecay 0.999 --dqnAgent_lr 0.03593813663804626
	python3 RLalgos.py --dqnAgent_epsDecay 0.999 --dqnAgent_lr 0.1
	python3 RLalgos.py --dqnAgent_epsDecay 0.988 --dqnAgent_lr 1e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.988 --dqnAgent_lr 2.782559402207126e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.988 --dqnAgent_lr 7.742636826811278e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.988 --dqnAgent_lr 0.00021544346900318823
	python3 RLalgos.py --dqnAgent_epsDecay 0.988 --dqnAgent_lr 0.0005994842503189409
	python3 RLalgos.py --dqnAgent_epsDecay 0.988 --dqnAgent_lr 0.0016681005372000592
	python3 RLalgos.py --dqnAgent_epsDecay 0.988 --dqnAgent_lr 0.004641588833612777
	python3 RLalgos.py --dqnAgent_epsDecay 0.988 --dqnAgent_lr 0.012915496650148827
	python3 RLalgos.py --dqnAgent_epsDecay 0.988 --dqnAgent_lr 0.03593813663804626
	python3 RLalgos.py --dqnAgent_epsDecay 0.988 --dqnAgent_lr 0.1
	python3 RLalgos.py --dqnAgent_epsDecay 0.977 --dqnAgent_lr 1e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.977 --dqnAgent_lr 2.782559402207126e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.977 --dqnAgent_lr 7.742636826811278e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.977 --dqnAgent_lr 0.00021544346900318823
	python3 RLalgos.py --dqnAgent_epsDecay 0.977 --dqnAgent_lr 0.0005994842503189409
	python3 RLalgos.py --dqnAgent_epsDecay 0.977 --dqnAgent_lr 0.0016681005372000592
	python3 RLalgos.py --dqnAgent_epsDecay 0.977 --dqnAgent_lr 0.004641588833612777
	python3 RLalgos.py --dqnAgent_epsDecay 0.977 --dqnAgent_lr 0.012915496650148827
	python3 RLalgos.py --dqnAgent_epsDecay 0.977 --dqnAgent_lr 0.03593813663804626
	python3 RLalgos.py --dqnAgent_epsDecay 0.977 --dqnAgent_lr 0.1
	python3 RLalgos.py --dqnAgent_epsDecay 0.966 --dqnAgent_lr 1e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.966 --dqnAgent_lr 2.782559402207126e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.966 --dqnAgent_lr 7.742636826811278e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.966 --dqnAgent_lr 0.00021544346900318823
	python3 RLalgos.py --dqnAgent_epsDecay 0.966 --dqnAgent_lr 0.0005994842503189409
	python3 RLalgos.py --dqnAgent_epsDecay 0.966 --dqnAgent_lr 0.0016681005372000592
	python3 RLalgos.py --dqnAgent_epsDecay 0.966 --dqnAgent_lr 0.004641588833612777
	python3 RLalgos.py --dqnAgent_epsDecay 0.966 --dqnAgent_lr 0.012915496650148827
	python3 RLalgos.py --dqnAgent_epsDecay 0.966 --dqnAgent_lr 0.03593813663804626
	python3 RLalgos.py --dqnAgent_epsDecay 0.966 --dqnAgent_lr 0.1
	python3 RLalgos.py --dqnAgent_epsDecay 0.955 --dqnAgent_lr 1e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.955 --dqnAgent_lr 2.782559402207126e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.955 --dqnAgent_lr 7.742636826811278e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.955 --dqnAgent_lr 0.00021544346900318823
	python3 RLalgos.py --dqnAgent_epsDecay 0.955 --dqnAgent_lr 0.0005994842503189409
	python3 RLalgos.py --dqnAgent_epsDecay 0.955 --dqnAgent_lr 0.0016681005372000592
	python3 RLalgos.py --dqnAgent_epsDecay 0.955 --dqnAgent_lr 0.004641588833612777
	python3 RLalgos.py --dqnAgent_epsDecay 0.955 --dqnAgent_lr 0.012915496650148827
	python3 RLalgos.py --dqnAgent_epsDecay 0.955 --dqnAgent_lr 0.03593813663804626
	python3 RLalgos.py --dqnAgent_epsDecay 0.955 --dqnAgent_lr 0.1
	python3 RLalgos.py --dqnAgent_epsDecay 0.9440000000000001 --dqnAgent_lr 1e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.9440000000000001 --dqnAgent_lr 2.782559402207126e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.9440000000000001 --dqnAgent_lr 7.742636826811278e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.9440000000000001 --dqnAgent_lr 0.00021544346900318823
	python3 RLalgos.py --dqnAgent_epsDecay 0.9440000000000001 --dqnAgent_lr 0.0005994842503189409
	python3 RLalgos.py --dqnAgent_epsDecay 0.9440000000000001 --dqnAgent_lr 0.0016681005372000592
	python3 RLalgos.py --dqnAgent_epsDecay 0.9440000000000001 --dqnAgent_lr 0.004641588833612777
	python3 RLalgos.py --dqnAgent_epsDecay 0.9440000000000001 --dqnAgent_lr 0.012915496650148827
	python3 RLalgos.py --dqnAgent_epsDecay 0.9440000000000001 --dqnAgent_lr 0.03593813663804626
	python3 RLalgos.py --dqnAgent_epsDecay 0.9440000000000001 --dqnAgent_lr 0.1
	python3 RLalgos.py --dqnAgent_epsDecay 0.933 --dqnAgent_lr 1e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.933 --dqnAgent_lr 2.782559402207126e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.933 --dqnAgent_lr 7.742636826811278e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.933 --dqnAgent_lr 0.00021544346900318823
	python3 RLalgos.py --dqnAgent_epsDecay 0.933 --dqnAgent_lr 0.0005994842503189409
	python3 RLalgos.py --dqnAgent_epsDecay 0.933 --dqnAgent_lr 0.0016681005372000592
	python3 RLalgos.py --dqnAgent_epsDecay 0.933 --dqnAgent_lr 0.004641588833612777
	python3 RLalgos.py --dqnAgent_epsDecay 0.933 --dqnAgent_lr 0.012915496650148827
	python3 RLalgos.py --dqnAgent_epsDecay 0.933 --dqnAgent_lr 0.03593813663804626
	python3 RLalgos.py --dqnAgent_epsDecay 0.933 --dqnAgent_lr 0.1
	python3 RLalgos.py --dqnAgent_epsDecay 0.922 --dqnAgent_lr 1e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.922 --dqnAgent_lr 2.782559402207126e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.922 --dqnAgent_lr 7.742636826811278e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.922 --dqnAgent_lr 0.00021544346900318823
	python3 RLalgos.py --dqnAgent_epsDecay 0.922 --dqnAgent_lr 0.0005994842503189409
	python3 RLalgos.py --dqnAgent_epsDecay 0.922 --dqnAgent_lr 0.0016681005372000592
	python3 RLalgos.py --dqnAgent_epsDecay 0.922 --dqnAgent_lr 0.004641588833612777
	python3 RLalgos.py --dqnAgent_epsDecay 0.922 --dqnAgent_lr 0.012915496650148827
	python3 RLalgos.py --dqnAgent_epsDecay 0.922 --dqnAgent_lr 0.03593813663804626
	python3 RLalgos.py --dqnAgent_epsDecay 0.922 --dqnAgent_lr 0.1
	python3 RLalgos.py --dqnAgent_epsDecay 0.911 --dqnAgent_lr 1e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.911 --dqnAgent_lr 2.782559402207126e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.911 --dqnAgent_lr 7.742636826811278e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.911 --dqnAgent_lr 0.00021544346900318823
	python3 RLalgos.py --dqnAgent_epsDecay 0.911 --dqnAgent_lr 0.0005994842503189409
	python3 RLalgos.py --dqnAgent_epsDecay 0.911 --dqnAgent_lr 0.0016681005372000592
	python3 RLalgos.py --dqnAgent_epsDecay 0.911 --dqnAgent_lr 0.004641588833612777
	python3 RLalgos.py --dqnAgent_epsDecay 0.911 --dqnAgent_lr 0.012915496650148827
	python3 RLalgos.py --dqnAgent_epsDecay 0.911 --dqnAgent_lr 0.03593813663804626
	python3 RLalgos.py --dqnAgent_epsDecay 0.911 --dqnAgent_lr 0.1
	python3 RLalgos.py --dqnAgent_epsDecay 0.9 --dqnAgent_lr 1e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.9 --dqnAgent_lr 2.782559402207126e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.9 --dqnAgent_lr 7.742636826811278e-05
	python3 RLalgos.py --dqnAgent_epsDecay 0.9 --dqnAgent_lr 0.00021544346900318823
	python3 RLalgos.py --dqnAgent_epsDecay 0.9 --dqnAgent_lr 0.0005994842503189409
	python3 RLalgos.py --dqnAgent_epsDecay 0.9 --dqnAgent_lr 0.0016681005372000592
	python3 RLalgos.py --dqnAgent_epsDecay 0.9 --dqnAgent_lr 0.004641588833612777
	python3 RLalgos.py --dqnAgent_epsDecay 0.9 --dqnAgent_lr 0.012915496650148827
	python3 RLalgos.py --dqnAgent_epsDecay 0.9 --dqnAgent_lr 0.03593813663804626
	python3 RLalgos.py --dqnAgent_epsDecay 0.9 --dqnAgent_lr 0.1


# This is a quick check for timming.
# For thorough results, use the profile
# option
runT:
	echo "Simple timing analysis"
	../bin/run.sh -t

clean:
	../bin/clean.sh

# ---- Easy way of checking the functions ---------
checkLog:
	../bin/checkLog.sh

checkTime:
	../bin/checkTime.sh

test:
	python3 -m pytest ../tests

define string_to_insert
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

if on_rtd:
	html_theme = 'default'
else:  # only import and set the theme if we're building docs locally
	import sphinx_rtd_theme
	html_theme = 'sphinx_rtd_theme'
	html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
endef
export string_to_insert

doc:
	@echo 'Generating a fresh copy of the docs ...'
	@rm -rf ../docs
	@mkdir ../docs
	@sphinx-apidoc -F -o ../docs .
	@sed "s/^extensions.*/& 'sphinx.ext.napoleon','sphinx_markdown_builder',/"        ../docs/conf.py   > ../docs/conf2.py
	@sed "s/^# import/import/"                              ../docs/conf2.py  > ../docs/conf3.py
	@sed "s/^# sys.path./sys.path./"                        ../docs/conf3.py  > ../docs/conf4.py
	@sed "s|^html_theme =|#html_theme =|"  					../docs/conf4.py  > ../docs/conf5.py
	@echo '# napoleon extensions over here '                >> ../docs/conf1.py
	@echo '# ------------------------------'                >> ../docs/conf1.py
	@echo 'napoleon_google_docstring = True'                >> ../docs/conf1.py
	@echo 'napoleon_numpy_docstring = True'                 >> ../docs/conf1.py
	@echo 'napoleon_include_init_with_doc = False'          >> ../docs/conf1.py
	@echo 'napoleon_include_private_with_doc = False'       >> ../docs/conf1.py
	@echo 'napoleon_include_special_with_doc = True'        >> ../docs/conf1.py
	@echo 'napoleon_use_admonition_for_examples = False'    >> ../docs/conf1.py
	@echo 'napoleon_use_admonition_for_notes = False'       >> ../docs/conf1.py
	@echo 'napoleon_use_admonition_for_references = False'  >> ../docs/conf1.py
	@echo 'napoleon_use_ivar = False'                       >> ../docs/conf1.py
	@echo 'napoleon_use_param = True'                       >> ../docs/conf1.py
	@echo 'napoleon_use_rtype = True'                       >> ../docs/conf1.py
	@echo ''                                                >> ../docs/conf1.py
	@echo ''                                                >> ../docs/conf1.py
	@echo "$$string_to_insert" 								>> ../docs/conf1.py
	@cat ../docs/conf5.py ../docs/conf1.py > ../docs/conf6.py
	@rm ../docs/conf.py ../docs/conf1.py ../docs/conf2.py ../docs/conf3.py ../docs/conf4.py ../docs/conf5.py
	@mv ../docs/conf6.py ../docs/conf.py
	@echo 'Generating the doc tree ....'
	@echo '----------------------------'
	sphinx-build -b html -aE -d ../docs/doctrees -c ../docs ../docs ../docs/_build/html
	sphinx-build -b markdown -aE -d ../docs/doctrees -c ../docs ../docs ../docs/_build/markdown
	cp -R ../docs/_build/markdown ../docs1
	rm -rf ../docs
	mv ../docs1 ../docs



